from agent.prompts.system_prompts import (
    DEVELOPER_ADVOCATE_SYSTEM_PROMPT,
    APPLICATION_IDENTITY,
    INTERVIEW_SYSTEM_PROMPT,
)

__all__ = [
    "DEVELOPER_ADVOCATE_SYSTEM_PROMPT",
    "APPLICATION_IDENTITY",
    "INTERVIEW_SYSTEM_PROMPT",
]
